name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test_ui:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
        working-directory: ME+EM_Take_Home_Test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ME+EM_Take_Home_Test
      - name: Run Playwright tests
        run: xvfb-run npx playwright test --grep @UI
        working-directory: ME+EM_Take_Home_Test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-ui
          path: playwright-report/
          retention-days: 30

       
