name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: npm install
      working-directory: ME+EM_Take_Home_Test

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ME+EM_Take_Home_Test

    - name: Run Playwright tests
      run: npx playwright test
      working-directory: ME+EM_Take_Home_Test

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: ME+EM_Take_Home_Test/playwright-report/
        retention-days: 30
